import React from 'react'

export const cars = [
  { 
    id: 1,
    brandy: "Benz",
    image: "https://wallpapercg.com/media/ts_2x/15475.webp",
    name: "Mercedes S-Class",
    description: "A premium luxury sedan with cutting-edge technology.",
    specs1: "Engine: V8",
    specs2: "Top Speed: 155 mph",
    specs3: "Transmission: Manual",
  },
  { 
    id: 2,
    brandy: "Benz",
    image: "https://imgs.search.brave.com/n_W_5uGHZrvxcOyVuo8JfPcABGMAsaQmUkJk-tD3flk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMwLmNhcmJ1enpp/bWFnZXMuY29tL3dv/cmRwcmVzcy93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyNC8wNi8y/M2MwMDIyXzAwNy5q/cGc",
    name: "Mercedes E-Class",
    description: "A midsize luxury sedan with advanced comfort and performance.",
    specs1: "Engine: 3.0L Turbocharged",
    specs2: "Top Speed: 130 mph",
    specs3: "Transmission: Automatic",
  },
  { 
    id: 3,
    brandy: "Benz",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Festival_automobile_international_2015_-_Mercedes_AMG_GT_-_003.jpg",
    name: "Mercedes AMG GT",
    description: "A high-performance sports car with aggressive styling.",
    specs1: "Engine: 4.0L Twin-Turbo V8",
    specs2: "Top Speed: 190 mph",
    specs3: "Transmission: 9-Speed Automatic",
  },
  { 
    id: 4,
    brandy: "Benz",
    image: "https://www.cnet.com/a/img/resize/77223ca410f4992359e3c911d9a012f380dee094/hub/2022/02/11/27dc2fbf-8935-43ad-9f68-1f1784d8a7fc/2021-mercedes-amg-g63-china-blue-113.jpg?auto=webp&width=1200",
    name: "Mercedes G-Wagon",
    description: "An iconic luxury SUV with exceptional off-road capability.",
    specs1: "Engine: 4.0L V8 Biturbo",
    specs2: "Top Speed: 149 mph",
    specs3: "Transmission: 9-Speed Automatic",
  },
  { 
    id: 5,
    brandy: "Benz",
    image: "https://cdni.autocarindia.com/ExtraImages/20211029115021_Mercedes_SL_63_2021_exterior_1.jpg",
    name: "Mercedes SL Roadster",
    description: "A stylish convertible blending luxury with open-top excitement.",
    specs1: "Engine: 3.0L Turbocharged Inline-6",
    specs2: "Top Speed: 155 mph",
    specs3: "Transmission: 9-Speed Automatic",
  },
  { 
    id: 6,
    brandy: "Benz",
    image: "https://images.carandbike.com/cms/articles/3202736/articles/3202866/2022_Mercedes_EQS_580_Review_a884f3fcd5.jpg",
    name: "Mercedes EQS",
    description: "A futuristic all-electric luxury sedan with top-tier tech.",
    specs1: "Battery: 107.8 kWh Lithium-ion",
    specs2: "Range: 350 miles per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
 
  { id: 7,
    brandy: "Audi",
    image: "https://stat.overdrive.in/wp-content/uploads/2017/10/2018-Audi-A8-A8L-8.jpg",
    name: "Audi A8",
    description: "A full-size luxury sedan with cutting-edge technology and supreme comfort.",
    specs1: "Engine: 4.0L Twin-Turbo V8",
    specs2: "Top Speed: 155 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 8,
    brandy: "Audi",
    image: "https://www.cnet.com/a/img/resize/dc0eba421ebed7f4525e8a4167d41269470ac729/hub/2020/09/03/720fe8d8-f827-462c-be9d-d52df3e8b7f8/ogi1-2020-audi-r8-spyder-001.jpg?auto=webp&fit=crop&height=675&width=1200",
    name: "Audi R8",
    description: "A high-performance supercar with a naturally aspirated V10 engine.",
    specs1: "Engine: 5.2L V10",
    specs2: "Top Speed: 205 mph",
    specs3: "Transmission: 7-Speed Dual-Clutch",
  },
  { 
    id: 9,
    brandy: "Audi",
    image: "https://www.topgear.com/sites/default/files/2024/09/35964-AUDIQ72024DEANSMITH10.jpg",
    name: "Audi Q7",
    description: "A luxury SUV with spacious seating and advanced driver assistance features.",
    specs1: "Engine: 3.0L Turbocharged V6",
    specs2: "Top Speed: 130 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 10,
    brandy: "Audi",
    image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Audi/e-tron-GT/8340/1678098767884/front-left-side-47.jpg",
    name: "Audi e-tron GT",
    description: "A high-performance electric sports sedan with breathtaking acceleration.",
    specs1: "Battery: 93.4 kWh Lithium-ion",
    specs2: "Range: 238 miles per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 11,
    brandy: "Audi",
    image: "https://imgd.aeplcdn.com/664x374/n/cw/ec/100073/rs5-exterior-left-rear-three-quarter.jpeg?isig=0&q=80",
    name: "Audi RS5",
    description: "A high-performance coupe with aggressive styling and exhilarating speed.",
    specs1: "Engine: 2.9L Twin-Turbo V6",
    specs2: "Top Speed: 174 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 12,
    brandy: "Audi",
    image: "https://cdni.autocarindia.com/ExtraImages/20150311101749_tt1.jpg",
    name: "Audi TT Roadster",
    description: "A stylish convertible blending fun, performance, and sleek design.",
    specs1: "Engine: 2.0L Turbocharged Inline-4",
    specs2: "Top Speed: 155 mph",
    specs3: "Transmission: 7-Speed Dual-Clutch",
  },
  { 
    id: 13,
    brandy: "BMW",
    image: "https://media.assettype.com/evoindia%2F2019-07%2F4d463a31-5554-40ea-a0f7-178e70123af0%2Fevoindia_import_2019_01_p90333060_highres.jpg",
    name: "BMW 7 Series",
    description: "A flagship luxury sedan with cutting-edge technology and superior comfort.",
    specs1: "Engine: 4.4L Twin-Turbo V8",
    specs2: "Top Speed: 155 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 14,
    brandy: "BMW",
    image: "https://images.prismic.io/exclusiveresorts/521030be-64d1-4525-a2d0-1fbab564218f_BMW+M4+001_ut2z6l-FullBleed_2880x1620.jpg?auto=compress,format&w=2560&q=70",
    name: "BMW M4",
    description: "A high-performance sports coupe with aggressive styling and track-ready power.",
    specs1: "Engine: 3.0L Twin-Turbo Inline-6",
    specs2: "Top Speed: 180 mph",
    specs3: "Transmission: 6-Speed Manual / 8-Speed Automatic",
  },
  { 
    id: 15,
    brandy: "BMW",
    image: "https://stimg.cardekho.com/images/carexteriorimages/630x420/BMW/X5-2023/10452/1688992642182/front-left-side-47.jpg",
    name: "BMW X5",
    description: "A luxury SUV with spacious interiors, powerful performance, and advanced tech.",
    specs1: "Engine: 3.0L Turbocharged Inline-6",
    specs2: "Top Speed: 130 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 16,
    brandy: "BMW",
    image: "https://www.bmw.in/content/dam/bmw/marketIN/bmw_in/all-models/i-series/ix/ix50/DI21_000054279%201.jpg",
    name: "BMW iX",
    description: "A futuristic all-electric SUV with long-range capability and premium features.",
    specs1: "Battery: 105.2 kWh Lithium-ion",
    specs2: "Range: 324 miles per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 17,
    brandy: "BMW",
    image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/BMW/Z4/10183/1685003672330/front-left-side-47.jpg",
    name: "BMW Z4",
    description: "A stylish roadster that delivers an exciting open-top driving experience.",
    specs1: "Engine: 2.0L Turbocharged Inline-4",
    specs2: "Top Speed: 155 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 18,
    brandy: "BMW",
    image: "https://www.bmw.in/content/dam/bmw/marketIN/bmw_in/all-models/m-series/M8-competition/m8-competition-coupe-header.jpg",
    name: "BMW M8 Competition",
    description: "A luxury grand tourer with an extreme level of performance and power.",
    specs1: "Engine: 4.4L Twin-Turbo V8",
    specs2: "Top Speed: 190 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 19,
    brandy: "Toyota",
    image: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202201/2022_Toyota_Camry_Hybrid-_Exte.jpg",
    name: "Toyota Camry",
    description: "A stylish and reliable midsize sedan with a comfortable ride.",
    specs1: "Engine: 2.5L Inline-4 / 3.5L V6",
    specs2: "Top Speed: 135 mph",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 20,
    brandy: "Toyota",
    image: "https://toyotagazooracing.com/-/media/TMC/tgr/global/contents/pressrelease/images/2024/0822-01/240822_ogp.jpg?la=ja-JP&rev=2cce1c4580304affa9f93fbdc3c9815c",
    name: "Toyota GR Supra",
    description: "A high-performance sports coupe with exhilarating speed and handling.",
    specs1: "Engine: 3.0L Turbocharged Inline-6",
    specs2: "Top Speed: 155 mph",
    specs3: "Transmission: 6-Speed Manual / 8-Speed Automatic",
  },
  { 
    id: 21,
    brandy: "Toyota",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIFtHB6UHkleaIDRbiNIxIwKoBjt7GXOwRpQ&s",
    name: "Toyota Land Cruiser",
    description: "A legendary off-road SUV with exceptional durability and power.",
    specs1: "Engine: 3.5L Twin-Turbo V6",
    specs2: "Top Speed: 130 mph",
    specs3: "Transmission: 10-Speed Automatic",
  },
  { 
    id: 22,
    brandy: "Toyota",
    image: "https://imageonthefly.autodatadirect.com/images/?width=1200&height=900&IMG=USD40TOC321A01300.jpg",
    name: "Toyota Prius",
    description: "A fuel-efficient hybrid known for its eco-friendly technology.",
    specs1: "Engine: 1.8L Hybrid Inline-4",
    specs2: "Top Speed: 112 mph",
    specs3: "Transmission: e-CVT",
  },
  { 
    id: 23,
    brandy: "Toyota",
    image: "https://media.ed.edmunds-media.com/toyota/tacoma/2025/oem/2025_toyota_tacoma_crew-cab-pickup_limited_fq_oem_1_1600.jpg",
    name: "Toyota Tacoma",
    description: "A rugged mid-size pickup truck built for adventure and durability.",
    specs1: "Engine: 3.5L V6",
    specs2: "Top Speed: 120 mph",
    specs3: "Transmission: 6-Speed Manual / 6-Speed Automatic",
  },
  { 
    id: 24,
    brandy: "Toyota",
    image: "https://imgd.aeplcdn.com/664x374/n/cw/ec/163403/bz4x-exterior-left-front-three-quarter.jpeg?isig=0&q=80",
    name: "Toyota bZ4X",
    description: "A fully electric SUV with modern design and advanced safety features.",
    specs1: "Battery: 71.4 kWh Lithium-ion",
    specs2: "Range: 250 miles per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 25,
    brandy: "Mahindra",
    image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mahindra/XUV700/10789/1705388477954/front-left-side-47.jpg",
    name: "Mahindra XUV700",
    description: "A premium SUV with advanced technology and powerful performance.",
    specs1: "Engine: 2.0L Turbocharged Petrol / 2.2L Diesel",
    specs2: "Top Speed: 180 km/h",
    specs3: "Transmission: 6-Speed Manual / Automatic",
  },
  { 
    id: 26,
    brandy: "Mahindra",
    image: "https://img.autocarpro.in/autocarpro/01eeafa8-4a73-4437-9bab-167dbcbbba5d_tharroxx.jpg?w=750&h=490&q=75&c=1",
    name: "Mahindra Thar",
    description: "An iconic off-road SUV built for adventure and rugged terrains.",
    specs1: "Engine: 2.0L mStallion Petrol / 2.2L mHawk Diesel",
    specs2: "Top Speed: 155 km/h",
    specs3: "Transmission: 6-Speed Manual / Automatic",
  },
  { 
    id: 27,
    brandy: "Mahindra",
    image: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mahindra/Scorpio-N/10817/1740050844896/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    name: "Mahindra Scorpio-N",
    description: "A bold and muscular SUV with a commanding road presence.",
    specs1: "Engine: 2.0L mStallion Petrol / 2.2L mHawk Diesel",
    specs2: "Top Speed: 165 km/h",
    specs3: "Transmission: 6-Speed Manual / Automatic",
  },
  { 
    id: 28,
    brandy: "Mahindra",
    image: "https://imgd.aeplcdn.com/1056x594/n/vl8rp0b_1638671.jpg?q=80",
    name: "Mahindra XUV400 EV",
    description: "A fully electric SUV with impressive range and futuristic design.",
    specs1: "Battery: 39.4 kWh Lithium-ion",
    specs2: "Range: 456 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 29,
    brandy: "Mahindra",
    image: "https://www.onelap.in/news/wp-content/uploads/2020/04/Bolero-pickup-featured-image.png",
    name: "Mahindra Bolero Pik-Up",
    description: "A reliable and sturdy pickup truck designed for commercial use.",
    specs1: "Engine: 2.5L m2DiCR Diesel",
    specs2: "Top Speed: 120 km/h",
    specs3: "Transmission: 5-Speed Manual",
  },
  { 
    id: 30,
    brandy: "Mahindra",
    image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mahindra/Marazzo/7948/1632224129922/front-left-side-47.jpg",
    name: "Mahindra Marazzo",
    description: "A spacious MPV with a comfortable and premium interior.",
    specs1: "Engine: 1.5L Turbo Diesel",
    specs2: "Top Speed: 145 km/h",
    specs3: "Transmission: 6-Speed Manual",
  },
  { 
    id: 31,
    brandy: "Hyundai",
    image: "https://source.unsplash.com/400x300/?hyundai-sedan",
    name: "Hyundai Elantra",
    description: "A stylish and fuel-efficient sedan with modern technology.",
    specs1: "Engine: 2.0L Inline-4 / 1.6L Turbocharged",
    specs2: "Top Speed: 210 km/h",
    specs3: "Transmission: 6-Speed Manual / CVT",
  },
  { 
    id: 32,
    brandy: "Hyundai",
    image: "https://source.unsplash.com/400x300/?hyundai-suv",
    name: "Hyundai Creta",
    description: "A compact SUV with a premium interior and advanced features.",
    specs1: "Engine: 1.5L Petrol / 1.5L Diesel",
    specs2: "Top Speed: 170 km/h",
    specs3: "Transmission: 6-Speed Manual / Automatic",
  },
  { 
    id: 33,
    brandy: "Hyundai",
    image: "https://source.unsplash.com/400x300/?hyundai-electric",
    name: "Hyundai Ioniq 5",
    description: "A futuristic all-electric SUV with a long driving range.",
    specs1: "Battery: 72.6 kWh Lithium-ion",
    specs2: "Range: 480 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 34,
    brandy: "Hyundai",
    image: "https://source.unsplash.com/400x300/?hyundai-sports",
    name: "Hyundai i20 N Line",
    description: "A sporty hatchback with dynamic performance and aggressive styling.",
    specs1: "Engine: 1.0L Turbocharged Petrol",
    specs2: "Top Speed: 190 km/h",
    specs3: "Transmission: 6-Speed iMT / 7-Speed DCT",
  },
  { 
    id: 35,
    brandy: "Hyundai",
    image: "https://source.unsplash.com/400x300/?hyundai-mpv",
    name: "Hyundai Alcazar",
    description: "A premium 7-seater SUV with spacious interiors and powerful performance.",
    specs1: "Engine: 2.0L Petrol / 1.5L Diesel",
    specs2: "Top Speed: 185 km/h",
    specs3: "Transmission: 6-Speed Manual / Automatic",
  },
  { 
    id: 36,
    brandy: "Hyundai",
    image: "https://source.unsplash.com/400x300/?hyundai-crossover",
    name: "Hyundai Venue",
    description: "A compact crossover with bold styling and advanced connectivity features.",
    specs1: "Engine: 1.2L Petrol / 1.0L Turbo Petrol",
    specs2: "Top Speed: 165 km/h",
    specs3: "Transmission: 5-Speed Manual / 7-Speed DCT",
  },
  { 
    id: 37,
    brandy: "MG",
    image: "https://source.unsplash.com/400x300/?mg-suv",
    name: "MG Hector",
    description: "A feature-packed midsize SUV with advanced technology and a bold design.",
    specs1: "Engine: 1.5L Turbo Petrol / 2.0L Diesel",
    specs2: "Top Speed: 170 km/h",
    specs3: "Transmission: 6-Speed Manual / CVT",
  },
  { 
    id: 38,
    brandy: "MG",
    image: "https://source.unsplash.com/400x300/?mg-electric",
    name: "MG ZS EV",
    description: "An all-electric compact SUV with impressive range and futuristic styling.",
    specs1: "Battery: 50.3 kWh Lithium-ion",
    specs2: "Range: 461 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 39,
    brandy: "MG",
    image: "https://source.unsplash.com/400x300/?mg-luxury",
    name: "MG Gloster",
    description: "A full-size premium SUV with luxurious interiors and ADAS technology.",
    specs1: "Engine: 2.0L Twin-Turbo Diesel",
    specs2: "Top Speed: 177 km/h",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 40,
    brandy: "MG",
    image: "https://source.unsplash.com/400x300/?mg-crossover",
    name: "MG Astor",
    description: "A compact crossover loaded with AI-powered technology and premium comfort.",
    specs1: "Engine: 1.3L Turbo Petrol / 1.5L Petrol",
    specs2: "Top Speed: 160 km/h",
    specs3: "Transmission: 6-Speed Manual / CVT",
  },
  { 
    id: 41,
    brandy: "MG",
    image: "https://source.unsplash.com/400x300/?mg-hatchback",
    name: "MG 3",
    description: "A stylish hatchback with a sporty design and efficient performance.",
    specs1: "Engine: 1.5L Petrol",
    specs2: "Top Speed: 175 km/h",
    specs3: "Transmission: 5-Speed Manual / CVT",
  },
  { 
    id: 42,
    brandy: "MG",
    image: "https://source.unsplash.com/400x300/?mg-performance",
    name: "MG Cyberster",
    description: "An all-electric roadster with cutting-edge performance and a futuristic design.",
    specs1: "Battery: 77 kWh Lithium-ion",
    specs2: "Top Speed: 200 km/h",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 43,
    brandy: "KIA",
    image: "https://source.unsplash.com/400x300/?kia-suv",
    name: "KIA Seltos",
    description: "A stylish and feature-rich compact SUV with modern technology.",
    specs1: "Engine: 1.5L Petrol / 1.5L Diesel / 1.4L Turbo Petrol",
    specs2: "Top Speed: 170 km/h",
    specs3: "Transmission: 6-Speed Manual / 7-Speed DCT",
  },
  { 
    id: 44,
    brandy: "KIA",
    image: "https://source.unsplash.com/400x300/?kia-mpv",
    name: "KIA Carens",
    description: "A premium 7-seater MPV with spacious interiors and advanced features.",
    specs1: "Engine: 1.5L Petrol / 1.5L Diesel / 1.4L Turbo Petrol",
    specs2: "Top Speed: 165 km/h",
    specs3: "Transmission: 6-Speed Manual / 7-Speed DCT",
  },
  { 
    id: 45,
    brandy: "KIA",
    image: "https://source.unsplash.com/400x300/?kia-electric",
    name: "KIA EV6",
    description: "A futuristic electric SUV with exceptional range and high performance.",
    specs1: "Battery: 77.4 kWh Lithium-ion",
    specs2: "Range: 528 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 46,
    brandy: "KIA",
    image: "https://source.unsplash.com/400x300/?kia-sedan",
    name: "KIA K5",
    description: "A premium midsize sedan with a sleek design and turbocharged engine options.",
    specs1: "Engine: 1.6L Turbo Petrol / 2.5L Turbo Petrol",
    specs2: "Top Speed: 210 km/h",
    specs3: "Transmission: 8-Speed Automatic / CVT",
  },
  { 
    id: 47,
    brandy: "KIA",
    image: "https://source.unsplash.com/400x300/?kia-crossover",
    name: "KIA Sonet",
    description: "A compact crossover with bold styling and advanced connectivity features.",
    specs1: "Engine: 1.2L Petrol / 1.0L Turbo Petrol / 1.5L Diesel",
    specs2: "Top Speed: 160 km/h",
    specs3: "Transmission: 5-Speed Manual / 7-Speed DCT",
  },
  { 
    id: 48,
    brandy: "KIA",
    image: "https://source.unsplash.com/400x300/?kia-luxury",
    name: "KIA Carnival",
    description: "A luxurious multi-purpose vehicle (MPV) with premium comfort and space.",
    specs1: "Engine: 2.2L Turbo Diesel",
    specs2: "Top Speed: 190 km/h",
    specs3: "Transmission: 8-Speed Automatic",
  },
  { 
    id: 49,
    brandy: "Tesla",
    image: "https://source.unsplash.com/400x300/?tesla-models",
    name: "Tesla Model S",
    description: "A high-performance luxury electric sedan with cutting-edge technology.",
    specs1: "Battery: 100 kWh Lithium-ion",
    specs2: "Range: 652 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 50,
    brandy: "Tesla",
    image: "https://source.unsplash.com/400x300/?tesla-model3",
    name: "Tesla Model 3",
    description: "An affordable electric sedan with an impressive driving range.",
    specs1: "Battery: 82 kWh Lithium-ion",
    specs2: "Range: 576 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 51,
    brandy: "Tesla",
    image: "https://source.unsplash.com/400x300/?tesla-modelx",
    name: "Tesla Model X",
    description: "A luxurious electric SUV with Falcon Wing doors and all-wheel drive.",
    specs1: "Battery: 100 kWh Lithium-ion",
    specs2: "Range: 547 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 52,
    brandy: "Tesla",
    image: "https://source.unsplash.com/400x300/?tesla-modely",
    name: "Tesla Model Y",
    description: "A versatile electric crossover with high performance and efficiency.",
    specs1: "Battery: 81 kWh Lithium-ion",
    specs2: "Range: 531 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 53,
    brandy: "Tesla",
    image: "https://source.unsplash.com/400x300/?tesla-cybertruck",
    name: "Tesla Cybertruck",
    description: "A futuristic all-electric pickup truck with an ultra-durable exoskeleton.",
    specs1: "Battery: 120 kWh Lithium-ion",
    specs2: "Range: 800 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  },
  { 
    id: 54,
    brandy: "Tesla",
    image: "https://source.unsplash.com/400x300/?tesla-roadster",
    name: "Tesla Roadster",
    description: "A high-performance electric supercar with mind-blowing acceleration.",
    specs1: "Battery: 200 kWh Lithium-ion",
    specs2: "Range: 1000 km per charge",
    specs3: "Transmission: Single-Speed Automatic",
  }
];










  